### ISSUE TITLE
Breakdown of a large file of 50 mb. And broken names

### ISSUE THREAD

**Issue by httsmvkcom** [HirbodBehnam/Downloader-Bot#2]
The file weighs 300 MB, but the bot broke it into 7 parts
![image](https://user-images.githubusercontent.com/51028674/77710362-d5e1f680-6fde-11ea-8aba-843dfe39b9ba.png)
The file is called 2020032017343822875.apk, but the bot renamed it. And so with all the files

**Comment by HirbodBehnam** [comment]
This is ok. Telegram API does not allow bots to upload files that are more than 50MB.
